{
 "title": "Dashboard for smartctl_exporter",
 "description": "prometheus-community\r\n/\r\nsmartctl_exporter\r\n",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Power On Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "smartctl_device_power_on_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Cycle Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "smartctl_device_power_cycle_count{instance=\"127.0.0.1:9003\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{job=\"fishtank\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk RPMs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "smartctl_device_rotation_rate{instance=\"127.0.0.1:9003\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Log Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_error_log_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMART STATUS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smartctl_device_smart_status", "legendFormat": "__auto" }
   ]
  }
 ]
}